server:
  port: 8082

spring:
  application:
    name: payment-gateway-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: ${SPRING_DATASOURCE_USERNAME:anshul}
    password: ${SPRING_DATASOURCE_PASSWORD:anshul123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY:aes-256-secret-key-for-card-data!}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

services:
  fraud-detection-url: ${FRAUD_DETECTION_URL:http://fraud-detection-service:8085}
  issuer-bank-url: ${ISSUER_BANK_URL:http://issuer-bank-simulator:8083}
  transaction-url: ${TRANSACTION_URL:http://transaction-service}

management:
  endpoints:
    web:
      exposure:
        include: health,info
